controller_manager:
  ros__parameters:
    update_rate: 400 # Hz
    inner_loop_rate: 400 # Hz
    outer_loop_rate: 50 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # TODO: add force sonsors
    # FL_foot_force_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # FR_foot_force_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # RL_foot_force_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # RR_foot_force_sensor_broadcaster:
    #   type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    unitree_controller:
      type: unitree_controller/UnitreeController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - FR_hip_joint 
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint 
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint 
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint 
      - RL_thigh_joint
      - RL_calf_joint
    state_interfaces:
      - position
      - velocity
      - effort

imu_sensor_broadcaster:
  ros__parameters:
    frame_id: imu_link
    sensor_name: imu_sensor

# TODO: add force sonsors
# FL_foot_force_sensor_broadcaster:
#   ros__parameters:
#     frame_id: FL_foot
#     sensor_name: FL_foot_force_sensor
#     # interface_names.force.z: FL_foot_force_sensor/force.z

# FR_foot_force_sensor_broadcaster:
#   ros__parameters:
#     frame_id: FR_foot
#     sensor_name: FR_foot_force_sensor
#     # interface_names.force.z: FR_foot_force_sensor/force.z

# RL_foot_force_sensor_broadcaster:
#   ros__parameters:
#     frame_id: RL_foot
#     sensor_name: RL_foot_force_sensor
#     # interface_names.force.z: RL_foot_force_sensor/force.z

# RR_foot_force_sensor_broadcaster:
#   ros__parameters:
#     frame_id: RR_foot
#     sensor_name: RR_foot_force_sensor
#     # interface_names.force.z: RR_foot_force_sensor/force.z

unitree_controller:
  ros__parameters:
    control_rate: 400.0
    # interfaces
    joints:
      - FR_hip_joint 
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint 
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint 
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint 
      - RL_thigh_joint
      - RL_calf_joint
    sensors:
      - imu_sensor
      # TODO: add force sonsors
      # - FL_foot_force_sensor
      # - FR_foot_force_sensor
      # - RL_foot_force_sensor
      # - RR_foot_force_sensor
    # joint PD gains
    kp_standing_up: 55.0
    kd_standing_up: 3.0
    kp_idling: 35.0
    kd_idling: 1.0
    kp_control: 5.0
    kd_control: 0.1
    kp_sitting_down: 10.0
    kd_sitting_down: 15.0
    # set control mode settings (in ms)
    min_zero_torque_duration_ms: 5000
    min_standing_up_duration_ms: 5000 
    min_idling_duration_ms: 5000 
    min_control_duration_ms: 5000
    min_sitting_down_duration_ms: 5000
    # InEKF (state estimator) settings
    inekf_settings:
      # contact estimator settings
      contact_estimator_settings: 
        beta0:
          LF: -30.0
          LH: -30.0
          RF: -30.0
          RH: -30.0
        beta1:
          LF: 2.0
          LH: 2.0
          RF: 2.0
          RH: 2.0
        contact_force_cov_alpha: 0.1
      # noise and LPF params
      contact_position_noise: 0.01
      contact_rotation_noise: 0.01
      lpf_lin_accel_cutoff: 250.0 
      lpf_dqJ_cutoff: 10.0 
      lpf_tauJ_cutoff: 10.0 
